language: generic

services:
  - docker

before_install:
  - docker build -t incubo-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true incubo-client npm test

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region ca-central-1)
  - docker build -t incubo-client ./client
  - docker build -t incubo-api ./api
  - docker build -t incubo-nginx ./nginx
  - docker tag incubo-client:latest 526452955669.dkr.ecr.ca-central-1.amazonaws.com/incubo-client:latest
  - docker tag incubo-api:latest 526452955669.dkr.ecr.ca-central-1.amazonaws.com/incubo-api:latest
  - docker tag incubo-nginx:latest 526452955669.dkr.ecr.ca-central-1.amazonaws.com/incubo-nginx:latest
  - docker push 526452955669.dkr.ecr.ca-central-1.amazonaws.com/incubo-client:latest
  - docker push 526452955669.dkr.ecr.ca-central-1.amazonaws.com/incubo-api:latest
  - docker push 526452955669.dkr.ecr.ca-central-1.amazonaws.com/incubo-nginx:latest

deploy:
  provider: elasticbeanstalk
  region: ca-central-1
  app: incubo
  env: Incubo-env-1
  bucket: elasticbeanstalk-ca-central-1-526452955669
  bucket_path: incubo
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY_ID'
  secret_access_key: '$AWS_SECRET_ACCESS_KEY'
